from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text, Float, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.base import Base

class Customer(Base):
    __tablename__ = "customers"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    customer_number = Column(String(50), unique=True)
    company_name = Column(String(255), nullable=False)
    customer_type = Column(String(50), default="b2b")  # b2b, b2c, government
    industry = Column(String(100))
    gstin = Column(String(20))
    pan = Column(String(15))
    credit_limit = Column(Float, default=0)
    credit_days = Column(Integer, default=30)
    payment_terms = Column(String(100))
    currency = Column(String(10), default="INR")
    billing_address = Column(Text)
    shipping_address = Column(Text)
    city = Column(String(100))
    state = Column(String(100))
    country = Column(String(100), default="India")
    pincode = Column(String(10))
    phone = Column(String(20))
    email = Column(String(255))
    website = Column(String(255))
    account_manager_id = Column(Integer, ForeignKey('users.id'), nullable=True)
    segment = Column(String(100))
    tags = Column(JSON, default=[])
    annual_revenue = Column(Float)
    employee_count = Column(Integer)
    status = Column(String(50), default="active")
    source = Column(String(100))
    lead_id = Column(Integer, nullable=True)
    custom_fields = Column(JSON, default={})
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    contacts = relationship("Contact", back_populates="customer")
    opportunities = relationship("Opportunity", back_populates="customer")

class Contact(Base):
    __tablename__ = "contacts"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    customer_id = Column(Integer, ForeignKey('customers.id'), nullable=False)
    first_name = Column(String(100), nullable=False)
    last_name = Column(String(100))
    designation = Column(String(100))
    department = Column(String(100))
    email = Column(String(255))
    phone = Column(String(20))
    mobile = Column(String(20))
    is_primary = Column(Boolean, default=False)
    is_decision_maker = Column(Boolean, default=False)
    linkedin_url = Column(String(500))
    notes = Column(Text)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    customer = relationship("Customer", back_populates="contacts")

class Opportunity(Base):
    __tablename__ = "opportunities"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    opportunity_number = Column(String(50), unique=True)
    name = Column(String(255), nullable=False)
    customer_id = Column(Integer, ForeignKey('customers.id'), nullable=False)
    contact_id = Column(Integer, ForeignKey('contacts.id'), nullable=True)
    stage = Column(String(100), default="prospecting")
    probability = Column(Float, default=10)
    expected_revenue = Column(Float)
    expected_close_date = Column(DateTime(timezone=True))
    actual_close_date = Column(DateTime(timezone=True))
    lost_reason = Column(String(255))
    description = Column(Text)
    assigned_to = Column(Integer, ForeignKey('users.id'), nullable=True)
    lead_source = Column(String(100))
    product_interest = Column(JSON, default=[])
    next_action = Column(String(255))
    next_action_date = Column(DateTime(timezone=True))
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    customer = relationship("Customer", back_populates="opportunities")

class Activity(Base):
    __tablename__ = "crm_activities"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    entity_type = Column(String(50))  # customer, opportunity, contact
    entity_id = Column(Integer)
    activity_type = Column(String(50))
    subject = Column(String(255))
    description = Column(Text)
    scheduled_at = Column(DateTime(timezone=True))
    completed_at = Column(DateTime(timezone=True))
    outcome = Column(String(255))
    created_by = Column(Integer, ForeignKey('users.id'))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
