from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text, Float, JSON, Numeric
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.base import Base

class Vendor(Base):
    __tablename__ = "vendors"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    vendor_number = Column(String(50), unique=True)
    company_name = Column(String(255), nullable=False)
    vendor_type = Column(String(50), default="supplier")
    gstin = Column(String(20))
    pan = Column(String(15))
    msme_number = Column(String(50))
    msme_category = Column(String(20))  # micro, small, medium
    credit_days = Column(Integer, default=30)
    payment_terms = Column(String(100))
    currency = Column(String(10), default="INR")
    billing_address = Column(Text)
    city = Column(String(100))
    state = Column(String(100))
    country = Column(String(100), default="India")
    phone = Column(String(20))
    email = Column(String(255))
    website = Column(String(255))
    bank_name = Column(String(100))
    bank_account = Column(String(50))
    bank_ifsc = Column(String(20))
    rating = Column(Float, default=0)
    status = Column(String(50), default="active")
    tags = Column(JSON, default=[])
    notes = Column(Text)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    purchase_orders = relationship("PurchaseOrder", back_populates="vendor")

class PurchaseOrder(Base):
    __tablename__ = "purchase_orders"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    po_number = Column(String(50), unique=True, nullable=False)
    vendor_id = Column(Integer, ForeignKey('vendors.id'), nullable=False)
    status = Column(String(50), default="draft")
    order_date = Column(DateTime(timezone=True), server_default=func.now())
    expected_delivery = Column(DateTime(timezone=True))
    delivery_address = Column(Text)
    subtotal = Column(Numeric(15,2), default=0)
    tax_amount = Column(Numeric(15,2), default=0)
    total_amount = Column(Numeric(15,2), default=0)
    currency = Column(String(10), default="INR")
    payment_terms = Column(String(100))
    notes = Column(Text)
    approved_by = Column(Integer, ForeignKey('users.id'), nullable=True)
    approved_at = Column(DateTime(timezone=True))
    created_by = Column(Integer, ForeignKey('users.id'))
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    items = relationship("PurchaseOrderItem", back_populates="purchase_order", cascade="all, delete-orphan")
    vendor = relationship("Vendor", back_populates="purchase_orders")
    goods_receipts = relationship("GoodsReceipt", back_populates="purchase_order")

class PurchaseOrderItem(Base):
    __tablename__ = "purchase_order_items"
    id = Column(Integer, primary_key=True)
    po_id = Column(Integer, ForeignKey('purchase_orders.id'), nullable=False)
    product_id = Column(Integer, ForeignKey('products.id'), nullable=True)
    description = Column(String(500))
    quantity = Column(Float, nullable=False)
    received_quantity = Column(Float, default=0)
    unit = Column(String(50))
    unit_price = Column(Numeric(15,2))
    tax_percent = Column(Float, default=18)
    tax_amount = Column(Numeric(15,2), default=0)
    line_total = Column(Numeric(15,2))
    hsn_code = Column(String(20))
    purchase_order = relationship("PurchaseOrder", back_populates="items")

class GoodsReceipt(Base):
    __tablename__ = "goods_receipts"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    grn_number = Column(String(50), unique=True)
    purchase_order_id = Column(Integer, ForeignKey('purchase_orders.id'))
    vendor_id = Column(Integer, ForeignKey('vendors.id'))
    warehouse_id = Column(Integer, ForeignKey('warehouses.id'))
    receipt_date = Column(DateTime(timezone=True), server_default=func.now())
    vendor_invoice_number = Column(String(100))
    status = Column(String(50), default="pending")
    notes = Column(Text)
    received_by = Column(Integer, ForeignKey('users.id'))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    purchase_order = relationship("PurchaseOrder", back_populates="goods_receipts")
