from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text, Float, JSON, Numeric
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.base import Base

class SalesOrder(Base):
    __tablename__ = "sales_orders"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    order_number = Column(String(50), unique=True, nullable=False)
    customer_id = Column(Integer, ForeignKey('customers.id'), nullable=False)
    branch_id = Column(Integer, nullable=True)
    status = Column(String(50), default="draft")
    order_date = Column(DateTime(timezone=True), server_default=func.now())
    delivery_date = Column(DateTime(timezone=True))
    payment_terms = Column(String(100))
    payment_status = Column(String(50), default="pending")
    shipping_address = Column(Text)
    billing_address = Column(Text)
    subtotal = Column(Numeric(15,2), default=0)
    discount_amount = Column(Numeric(15,2), default=0)
    tax_amount = Column(Numeric(15,2), default=0)
    total_amount = Column(Numeric(15,2), default=0)
    currency = Column(String(10), default="INR")
    notes = Column(Text)
    assigned_to = Column(Integer, ForeignKey('users.id'), nullable=True)
    opportunity_id = Column(Integer, nullable=True)
    purchase_order_number = Column(String(100))
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    items = relationship("SalesOrderItem", back_populates="order", cascade="all, delete-orphan")
    invoices = relationship("Invoice", back_populates="sales_order")

class SalesOrderItem(Base):
    __tablename__ = "sales_order_items"
    id = Column(Integer, primary_key=True)
    order_id = Column(Integer, ForeignKey('sales_orders.id'), nullable=False)
    product_id = Column(Integer, ForeignKey('products.id'), nullable=True)
    description = Column(String(500))
    quantity = Column(Float, nullable=False, default=1)
    unit = Column(String(50))
    unit_price = Column(Numeric(15,2), nullable=False)
    discount_percent = Column(Float, default=0)
    tax_percent = Column(Float, default=18)
    tax_amount = Column(Numeric(15,2), default=0)
    line_total = Column(Numeric(15,2), default=0)
    hsn_code = Column(String(20))
    order = relationship("SalesOrder", back_populates="items")

class Invoice(Base):
    __tablename__ = "invoices"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    invoice_number = Column(String(50), unique=True, nullable=False)
    customer_id = Column(Integer, ForeignKey('customers.id'), nullable=False)
    sales_order_id = Column(Integer, ForeignKey('sales_orders.id'), nullable=True)
    status = Column(String(50), default="draft")
    invoice_date = Column(DateTime(timezone=True), server_default=func.now())
    due_date = Column(DateTime(timezone=True))
    subtotal = Column(Numeric(15,2), default=0)
    discount_amount = Column(Numeric(15,2), default=0)
    cgst_amount = Column(Numeric(15,2), default=0)
    sgst_amount = Column(Numeric(15,2), default=0)
    igst_amount = Column(Numeric(15,2), default=0)
    total_amount = Column(Numeric(15,2), default=0)
    amount_paid = Column(Numeric(15,2), default=0)
    balance_due = Column(Numeric(15,2), default=0)
    currency = Column(String(10), default="INR")
    notes = Column(Text)
    terms = Column(Text)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    items = relationship("InvoiceItem", back_populates="invoice", cascade="all, delete-orphan")
    payments = relationship("Payment", back_populates="invoice")
    sales_order = relationship("SalesOrder", back_populates="invoices")

class InvoiceItem(Base):
    __tablename__ = "invoice_items"
    id = Column(Integer, primary_key=True)
    invoice_id = Column(Integer, ForeignKey('invoices.id'), nullable=False)
    product_id = Column(Integer, ForeignKey('products.id'), nullable=True)
    description = Column(String(500))
    quantity = Column(Float, default=1)
    unit = Column(String(50))
    unit_price = Column(Numeric(15,2))
    discount_percent = Column(Float, default=0)
    cgst_percent = Column(Float, default=9)
    sgst_percent = Column(Float, default=9)
    igst_percent = Column(Float, default=0)
    line_total = Column(Numeric(15,2))
    hsn_code = Column(String(20))
    invoice = relationship("Invoice", back_populates="items")

class Payment(Base):
    __tablename__ = "payments"
    id = Column(Integer, primary_key=True)
    tenant_id = Column(Integer, nullable=True)
    payment_number = Column(String(50), unique=True)
    invoice_id = Column(Integer, ForeignKey('invoices.id'), nullable=True)
    customer_id = Column(Integer, ForeignKey('customers.id'))
    amount = Column(Numeric(15,2), nullable=False)
    payment_date = Column(DateTime(timezone=True))
    payment_mode = Column(String(50))  # cash, cheque, neft, rtgs, upi
    reference_number = Column(String(100))
    bank_name = Column(String(100))
    notes = Column(Text)
    status = Column(String(50), default="completed")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    invoice = relationship("Invoice", back_populates="payments")
